name: "Copy To S3"
description: "AWS S3 cp"
author: memememe
      
inputs:
  source:
    description: |-
      The name of the key or the file to take as source
    required: True
  dest:
    description: |-
      The name of the key or the file to take as destination
    required: True
  aws_region:
    description: |-
      The region where the data will be stored (if the destination is s3)
    required: False
    default: us-east-1
    
runs:
  using: docker
  image: Dockerfile
  
branding:
  icon: refresh-cw
  color: green
